CREATE TABLE ROLE (
	ROLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ROLE_NAME VARCHAR ( 255 ) NOT NULL,
	CREATED_DATE DATETIME NULL,
	CREATED_BY BIGINT NULL,
	MODIFIED_DATE DATETIME NULL,
	MODIFIED_BY BIGINT NULL 
);
CREATE TABLE USER (
	USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	USER_NAME VARCHAR ( 64 ),
	DISPLAY_NAME VARCHAR ( 64 ),
	EMAIL VARCHAR ( 128 ) NOT NULL UNIQUE,
	PHONE VARCHAR ( 15 ) NOT NULL UNIQUE,
	PWD_HASH VARCHAR ( 32 ),
	PWD_SALT VARCHAR ( 32 ),
	EXTERNAL_TYPE VARCHAR ( 16 ),-- EXTERNAL-AUTH TYPE & ID.
	EXTERNAL_ID VARCHAR ( 64 ),
	CREATED_DATE DATETIME NULL,
	CREATED_BY BIGINT NULL,
	MODIFIED_DATE DATETIME NULL,
	MODIFIED_BY BIGINT NULL 
);
CREATE TABLE ADMIN (
	ADMIN_ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ROLE_ID BIGINT NULL,-- TEMP NULL IN PROCESS R&D
	ADMIN_NAME VARCHAR ( 64 ),
	DISPLAY_NAME VARCHAR ( 64 ),
	EMAIL VARCHAR ( 128 ) NOT NULL UNIQUE,
	PHONE VARCHAR ( 15 ) NOT NULL UNIQUE,
	PWD_HASH VARCHAR ( 32 ),
	PWD_SALT VARCHAR ( 32 ),
	CREATED_DATE DATETIME NULL,
	CREATED_BY BIGINT NULL,
	MODIFIED_DATE DATETIME NULL,
	MODIFIED_BY BIGINT NULL 
);
